acsacs_dynhost_list:
    pattern:  /dynhosts/
    defaults: { _controller: ACSACSPanelDynHostBundle:DynHostController:index }

ACSACSPanelDynHostBundle_dynhostsetup:
    resource: "@ACSACSPanelDynHostBundle/Resources/config/routing/dynhostsetup.yml"
    prefix:   /dynhostsetup

