parameters:
#    acsacs_panel_wordpress.example.class: ACS\ACSPanelWordpressBundle\Example

services:
## Menu items added with event listener
    dynhost_menu_subscriber:
        class: ACS\ACSPanelDynHost\ACSACSPanelDynHostBundle\Event\Subscribers\DynHostMenuSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}


